// Code generated by scripts/gen-version-file.sh. DO NOT EDIT.
package version

func init(){
	b := &build_info
	b.Version   = "260619-r0"
	b.GitRev    = "bda904b44f66bc5cb22e75a694ad3678579744f5"
	b.GitDirty  = true
}
