// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: clade/v1/graph.proto

package cladev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Image is the metadata of a concrete tagged image as observed in a registry.
type Image struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fully qualified repository, e.g. "docker.io/library/golang".
	Repo string `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	// Tag, e.g. "1.22.3-alpine".
	Tag string `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	// Manifest digest, e.g. "sha256:...". Empty if the image does not exist.
	Digest string `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	// Creation time as reported by the image config.
	Created *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	// Image config labels.
	Labels        map[string]string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_clade_v1_graph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_clade_v1_graph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_clade_v1_graph_proto_rawDescGZIP(), []int{0}
}

func (x *Image) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *Image) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Image) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *Image) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *Image) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// Node is a buildable target image in the dependency graph. How it is built
// (Dockerfile, context, buildx options, ...) is read from the port's port.yaml
// at build time, so only the identity and dependency information is carried here.
type Node struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable identifier of the node; the target reference "repo:tag".
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Metadata of the target image. digest is empty when the target is absent.
	Image *Image `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	// Reference of the upstream (base) image, "repo:tag".
	// Passed to the build as the BASE build argument.
	Base string `protobuf:"bytes,3,opt,name=base,proto3" json:"base,omitempty"`
	// Directory of the port that produces this image.
	Port string `protobuf:"bytes,4,opt,name=port,proto3" json:"port,omitempty"`
	// Node ids of internal parents (i.e. bases that are themselves built by clade).
	// Empty when the base is an external upstream image.
	Parents []string `protobuf:"bytes,5,rep,name=parents,proto3" json:"parents,omitempty"`
	// True when the target image is out of date with respect to its base
	// (missing, older, or an ancestor is outdated).
	Outdated      bool `protobuf:"varint,6,opt,name=outdated,proto3" json:"outdated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_clade_v1_graph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_clade_v1_graph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_clade_v1_graph_proto_rawDescGZIP(), []int{1}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *Node) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *Node) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *Node) GetParents() []string {
	if x != nil {
		return x.Parents
	}
	return nil
}

func (x *Node) GetOutdated() bool {
	if x != nil {
		return x.Outdated
	}
	return false
}

// Graph is a serializable dependency graph of build target images.
// Nodes are ordered topologically (parents before children).
type Graph struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Graph) Reset() {
	*x = Graph{}
	mi := &file_clade_v1_graph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Graph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Graph) ProtoMessage() {}

func (x *Graph) ProtoReflect() protoreflect.Message {
	mi := &file_clade_v1_graph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Graph.ProtoReflect.Descriptor instead.
func (*Graph) Descriptor() ([]byte, []int) {
	return file_clade_v1_graph_proto_rawDescGZIP(), []int{2}
}

func (x *Graph) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_clade_v1_graph_proto protoreflect.FileDescriptor

const file_clade_v1_graph_proto_rawDesc = "" +
	"\n" +
	"\x14clade/v1/graph.proto\x12\bclade.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xeb\x01\n" +
	"\x05Image\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\tR\x06digest\x124\n" +
	"\acreated\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x123\n" +
	"\x06labels\x18\x05 \x03(\v2\x1b.clade.v1.Image.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9b\x01\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x05image\x18\x02 \x01(\v2\x0f.clade.v1.ImageR\x05image\x12\x12\n" +
	"\x04base\x18\x03 \x01(\tR\x04base\x12\x12\n" +
	"\x04port\x18\x04 \x01(\tR\x04port\x12\x18\n" +
	"\aparents\x18\x05 \x03(\tR\aparents\x12\x1a\n" +
	"\boutdated\x18\x06 \x01(\bR\boutdated\"-\n" +
	"\x05Graph\x12$\n" +
	"\x05nodes\x18\x01 \x03(\v2\x0e.clade.v1.NodeR\x05nodesB/Z-github.com/lesomnus/clade/pb/clade/v1;cladev1b\x06proto3"

var (
	file_clade_v1_graph_proto_rawDescOnce sync.Once
	file_clade_v1_graph_proto_rawDescData []byte
)

func file_clade_v1_graph_proto_rawDescGZIP() []byte {
	file_clade_v1_graph_proto_rawDescOnce.Do(func() {
		file_clade_v1_graph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clade_v1_graph_proto_rawDesc), len(file_clade_v1_graph_proto_rawDesc)))
	})
	return file_clade_v1_graph_proto_rawDescData
}

var file_clade_v1_graph_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_clade_v1_graph_proto_goTypes = []any{
	(*Image)(nil),                 // 0: clade.v1.Image
	(*Node)(nil),                  // 1: clade.v1.Node
	(*Graph)(nil),                 // 2: clade.v1.Graph
	nil,                           // 3: clade.v1.Image.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_clade_v1_graph_proto_depIdxs = []int32{
	4, // 0: clade.v1.Image.created:type_name -> google.protobuf.Timestamp
	3, // 1: clade.v1.Image.labels:type_name -> clade.v1.Image.LabelsEntry
	0, // 2: clade.v1.Node.image:type_name -> clade.v1.Image
	1, // 3: clade.v1.Graph.nodes:type_name -> clade.v1.Node
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_clade_v1_graph_proto_init() }
func file_clade_v1_graph_proto_init() {
	if File_clade_v1_graph_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clade_v1_graph_proto_rawDesc), len(file_clade_v1_graph_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clade_v1_graph_proto_goTypes,
		DependencyIndexes: file_clade_v1_graph_proto_depIdxs,
		MessageInfos:      file_clade_v1_graph_proto_msgTypes,
	}.Build()
	File_clade_v1_graph_proto = out.File
	file_clade_v1_graph_proto_goTypes = nil
	file_clade_v1_graph_proto_depIdxs = nil
}
