services:
  claude:
    image: ghcr.io/lesomnus/claude:2.1
    command: sh -c 'exec claude remote-control --spawn "$${RC_SPAWN:-same-dir}"'

    working_dir: /workspace
    hostname: ${COMPOSE_PROJECT_NAME}
    environment:
      CLAUDE_CONFIG_DIR: /home/hypnos/.claude
      RC_NAME: clade

    volumes:
      - go.cache.mod:/go/pkg/mod
      - go.cache.bin:/home/hypnos/.cache/go-build

      - ..:/workspace
      - ${HOME}/.claude:/home/hypnos/.claude

    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 8G
        reservations:
          cpus: "2"
          memory: 4G
