services:
  dev: &dev
    build:
      context: .
      dockerfile: Dockerfile

    command: sleep infinity

    privileged: true

    environment:
      CLAUDE_CONFIG_DIR: /home/hypnos/.claude
      RC_NAME: clade

    volumes:
      - command.history:/commandhistory
      - go.cache.mod:/go/pkg/mod
      - go.cache.bin:/home/hypnos/.cache/go-build

      - ..:/workspace
      - ${HOME}/workspaces:/workspaces
      - ${HOME}/.claude:/home/hypnos/.claude

    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 8G
          pids: 2048
        reservations:
          cpus: "2"
          memory: 4G

  claude:
    <<: *dev
    hostname: ${COMPOSE_PROJECT_NAME}
    command: sh -c 'exec claude remote-control --spawn "$${RC_SPAWN:-same-dir}"'
    restart: unless-stopped
    working_dir: /workspace
    tty: true

volumes:
  go.cache.mod:
  go.cache.bin:
  command.history:
